/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.ClsReserva;
import com.sv.udb.clases.ClsVentas;
import java.util.List;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class FrmPpal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPpal
     */
    public FrmPpal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.poblarData();
    }
    
    private void poblarData(){
        DefaultTableModel model = (DefaultTableModel)this.tblTodo.getModel();
        while(model.getRowCount()>0){
            model.removeRow(0);//limpia
        }
         
        ClsReserva obje = new ClsReserva();
        for(ClsVentas temp : obje.getData())
        {
            String text = String.format("%s", temp.getCompra());
            Object[] arre = new Object[3];
            arre[0] = text;
            arre[1] = temp.getTipo();
            arre[2] = temp.getNombre();
            model.addRow(arre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnDiesel = new javax.swing.JLabel();
        btnEspecial = new javax.swing.JLabel();
        btnRegular = new javax.swing.JLabel();
        lblDiesel = new javax.swing.JLabel();
        lblRegular = new javax.swing.JLabel();
        lblEspecial = new javax.swing.JLabel();
        lblPoDi = new javax.swing.JLabel();
        lblPoRe = new javax.swing.JLabel();
        lblPoEs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTodo = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Tipo de venta");

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad en dinero ", "Cantidad en galones" }));

        jLabel3.setText("Ingrese una cantidad");

        jLabel1.setText("Ingrese su nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOpcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(txtCliente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnDiesel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDiesel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/images/diesel.png"))); // NOI18N
        btnDiesel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDieselMouseClicked(evt);
            }
        });

        btnEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/images/regular.png"))); // NOI18N
        btnEspecial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspecialMouseClicked(evt);
            }
        });

        btnRegular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/images/especial.png"))); // NOI18N
        btnRegular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegularMouseClicked(evt);
            }
        });

        lblDiesel.setText("Diesel");

        lblRegular.setText("Regular");

        lblEspecial.setText("Especial");

        lblPoDi.setText("100%");

        lblPoRe.setText("100%");

        lblPoEs.setText("100%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPoDi)
                    .addComponent(btnDiesel)
                    .addComponent(lblDiesel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPoRe)
                    .addComponent(btnRegular)
                    .addComponent(lblRegular))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPoEs)
                    .addComponent(btnEspecial)
                    .addComponent(lblEspecial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiesel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegular)
                        .addComponent(lblEspecial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDiesel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspecial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegular, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoDi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPoRe)
                        .addComponent(lblPoEs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClsReserva Reserva = new ClsReserva();
    DecimalFormat formatter = new DecimalFormat("#0.00");
    
    private void btnDieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDieselMouseClicked
        int Tipo;
        double Valor;
        String Gas = "Diesel";
        
        Tipo = cmbOpcion.getSelectedIndex() + 1;
        Valor = Double.parseDouble(txtCantidad.getText());
        Reserva.setTipo(Tipo);
        Reserva.setCantidad(Valor);
        Reserva.realCompr(Gas);
        double Por;
        Por = Reserva.porcentaje(Gas);        
        this.lblPoDi.setText(formatter.format(Por) + "%");
        
        java.util.List<ClsVentas> nuevo = new ArrayList<>();
        ClsVentas agregar = new ClsVentas();
        agregar.setCompra(Double.toString(Reserva.getCantidad()));
        agregar.setNombre(txtCliente.getText());
        agregar.setTipo(Gas);
        nuevo.add(agregar);
        Reserva.Actualizar(nuevo);
        JOptionPane.showMessageDialog(this, "Datos actualizados! \nRevisar archivo.csv");
        
        this.poblarData();
    }//GEN-LAST:event_btnDieselMouseClicked

    private void btnRegularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegularMouseClicked
        int Tipo;
        double Valor;
        String Gas = "Regular";
        
        Tipo = cmbOpcion.getSelectedIndex() + 1;
        Valor = Double.parseDouble(txtCantidad.getText());
        Reserva.setTipo(Tipo);
        Reserva.setCantidad(Valor);
        Reserva.realCompr(Gas);
        double Por;
        Por = Reserva.porcentaje(Gas);        
        this.lblPoRe.setText(formatter.format(Por) + "%");
        
        java.util.List<ClsVentas> nuevo = new ArrayList<>();
        ClsVentas agregar = new ClsVentas();
        agregar.setCompra(Double.toString(Reserva.getCantidad()));
        agregar.setNombre(txtCliente.getText());
        agregar.setTipo(Gas);
        nuevo.add(agregar);
        Reserva.Actualizar(nuevo);
        JOptionPane.showMessageDialog(this, "Datos actualizados! \nRevisar archivo.csv");
        
        this.poblarData();
    }//GEN-LAST:event_btnRegularMouseClicked

    private void btnEspecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialMouseClicked
        int Tipo;
        double Valor;
        String Gas = "Especial";
        
        Tipo = cmbOpcion.getSelectedIndex() + 1;
        Valor = Double.parseDouble(txtCantidad.getText());
        Reserva.setTipo(Tipo);
        Reserva.setCantidad(Valor);
        Reserva.realCompr(Gas);
        double Por;
        Por = Reserva.porcentaje(Gas);        
        this.lblPoEs.setText(formatter.format(Por) + "%");
        
        java.util.List<ClsVentas> nuevo = new ArrayList<>();
        ClsVentas agregar = new ClsVentas();
        agregar.setCompra(Double.toString(Reserva.getCantidad()));
        agregar.setNombre(txtCliente.getText());
        agregar.setTipo(Gas);
        nuevo.add(agregar);
        Reserva.Actualizar(nuevo);
        JOptionPane.showMessageDialog(this, "Datos actualizados! \nRevisar archivo.csv");
        
        this.poblarData();
    }//GEN-LAST:event_btnEspecialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDiesel;
    private javax.swing.JLabel btnEspecial;
    private javax.swing.JLabel btnRegular;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiesel;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblPoDi;
    private javax.swing.JLabel lblPoEs;
    private javax.swing.JLabel lblPoRe;
    private javax.swing.JLabel lblRegular;
    private javax.swing.JTable tblTodo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
